on: [push]
name: build

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install APT packages
      if: matrix.platform == 'ubuntu-latest'
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -yq install \
        libalut-dev \
        libflac-dev \
        libfreetype-dev \
        libglu1-mesa-dev \
        libudev-dev \
        libvorbis-dev \
        libx11-dev \
        libxcursor-dev \
        libxrandr-dev

    - name: Configure
      run: cmake -B build
    - name: Build
      run: cmake --build build/
